### ISSUE TITLE
Crash on connection with severe packet loss

### ISSUE THREAD

**Issue by ksuprynowicz** [overte-org/overte#1265]
Log:
```
[0m[12/07 12:35:44] [DEBUG] [hifi.entities] Not setting web entity script URL since "" cannot be parsed to a valid URL.
[0m[12/07 12:35:44] [DEBUG] [hifi.qml] Upating offscreen textures to  1129  x  652
[0m[12/07 12:35:44] [DEBUG] [overte.scriptengine] "Already downloading script at: http://oaktown.pl/script_editor/monaco-editor/samples/script-editor/editorEntity.js (retry: 0; scriptusers: 2)"
[0m[12/07 12:35:44] [DEBUG] [hifi.qml] Offscreen UI resizing to  1129 x 652
[New Thread 0x7ffeb17fa6c0 (LWP 115185)]
[New Thread 0x7ffea7fff6c0 (LWP 115187)]
[New Thread 0x7ffea57fa6c0 (LWP 115190)]
[New Thread 0x7ffebffff6c0 (LWP 115196)]
[New Thread 0x7ffec6afd6c0 (LWP 115199)]
[New Thread 0x7ffec62fc6c0 (LWP 115200)]
[New Thread 0x7ffec5afb6c0 (LWP 115201)]
[New Thread 0x7ffebf7fe6c0 (LWP 115202)]
[New Thread 0x7ffebe7fc6c0 (LWP 115203)]
[New Thread 0x7ffebdffb6c0 (LWP 115204)]
[New Thread 0x7ffebd7fa6c0 (LWP 115205)]
[New Thread 0x7ffeb37fe6c0 (LWP 115206)]
[0m[12/07 12:35:44] [DEBUG] [hifi.networking.asset_client] Got reply for asset:  "c548bd8a9864ae478bdbbf124cc693219204879f6325b8cadc73431e77266c4d"
[New Thread 0x7ffe5dffb6c0 (LWP 115217)]
[New Thread 0x7ffe5d7fa6c0 (LWP 115218)]
[New Thread 0x7ffe5cff96c0 (LWP 115219)]
[New Thread 0x7ffe537fe6c0 (LWP 115220)]
[New Thread 0x7ffe399bd6c0 (LWP 115221)]
[New Thread 0x7ffe391bc6c0 (LWP 115222)]
[New Thread 0x7ffe2c9fb6c0 (LWP 115226)]
[0m[12/07 12:35:45] [DEBUG] [hifi.networking] udt::Socket ( "UDP" QAbstractSocket::BoundState ) error -  0 QAbstractSocket::SocketError(22) ( "Unable to send a datagram" ) pending: 0  
[0m[12/07 12:35:45] [DEBUG] [hifi.networking] udt::writeDatagram ( QAbstractSocket::BoundState "UDP ""195.201.114.16":34313 ) error -  0 QAbstractSocket::SocketError(22) ( "Unable to send a datagram" ) pending: 0  
[0m[12/07 12:35:45] [DEBUG] [hifi.networking] Stats for  "UDP ""195.201.114.16":49161 
[12/07 12:35:45] [DEBUG] [hifi.networking]      Last Heard Microstamp:  1733592945183839  ( 31 usec ago)
[12/07 12:35:45] [DEBUG] [hifi.networking]      Outbound Kbps:  235.767 
[12/07 12:35:45] [DEBUG] [hifi.networking]      Inbound Kbps:  204.04 
[12/07 12:35:45] [DEBUG] [hifi.networking]      Ping:  706
[0m[12/07 12:35:45] [DEBUG] [hifi.networking] Stats for  "UDP ""195.201.114.16":45313 
[12/07 12:35:45] [DEBUG] [hifi.networking]      Last Heard Microstamp:  1733592945183766  ( 104 usec ago)
[12/07 12:35:45] [DEBUG] [hifi.networking]      Outbound Kbps:  60.4296 
[12/07 12:35:45] [DEBUG] [hifi.networking]      Inbound Kbps:  58.8937 
[12/07 12:35:45] [DEBUG] [hifi.networking]      Ping:  706
[0m[12/07 12:35:45] [DEBUG] [hifi.networking] Stats for  "UDP ""195.201.114.16":34313 
[12/07 12:35:45] [DEBUG] [hifi.networking]      Last Heard Microstamp:  1733592945183818  ( 52 usec ago)
[12/07 12:35:45] [DEBUG] [hifi.networking]      Outbound Kbps:  64.6775 
[12/07 12:35:45] [DEBUG] [hifi.networking]      Inbound Kbps:  161.202 
[12/07 12:35:45] [DEBUG] [hifi.networking]      Ping:  706
[0m[12/07 12:35:45] [DEBUG] [hifi.networking] Stats for  "UDP ""195.201.114.16":38321 
[12/07 12:35:45] [DEBUG] [hifi.networking]      Last Heard Microstamp:  1733592945164890  ( 18980 usec ago)
[12/07 12:35:45] [DEBUG] [hifi.networking]      Outbound Kbps:  178.753 
[12/07 12:35:45] [DEBUG] [hifi.networking]      Inbound Kbps:  79.157 
[12/07 12:35:45] [DEBUG] [hifi.networking]      Ping:  706
[0m[12/07 12:35:45] [DEBUG] [hifi.networking] Stats for  "UDP ""195.201.114.16":34619 
[12/07 12:35:45] [DEBUG] [hifi.networking]      Last Heard Microstamp:  1733592944943276  ( 240594 usec ago)
[12/07 12:35:45] [DEBUG] [hifi.networking]      Outbound Kbps:  3.31187 
[12/07 12:35:45] [DEBUG] [hifi.networking]      Inbound Kbps:  1.10396 
[12/07 12:35:45] [DEBUG] [hifi.networking]      Ping:  706
[0m[12/07 12:35:45] [DEBUG] [hifi.networking] Stats for  "UDP ""195.201.114.16":58521 
[12/07 12:35:45] [DEBUG] [hifi.networking]      Last Heard Microstamp:  1733592944998638  ( 185232 usec ago)
[12/07 12:35:45] [DEBUG] [hifi.networking]      Outbound Kbps:  2.44791 
[12/07 12:35:45] [DEBUG] [hifi.networking]      Inbound Kbps:  5.1358 
[12/07 12:35:45] [DEBUG] [hifi.networking]      Ping:  706
malloc(): unaligned tcache chunk detected

Thread 444 "Networking: Sen" received signal SIGABRT, Aborted.
```
Backtrace (it seems to be incomplete):
```
#0  0x00007fffe9a7ec94 in __pthread_kill_implementation () from /lib64/libc.so.6
#1  0x00007fffe9a25d1e in raise () from /lib64/libc.so.6
#2  0x00007fffe9a0d942 in abort () from /lib64/libc.so.6
#3  0x00007fffe9a0e7a7 in __libc_message_impl.cold () from /lib64/libc.so.6
#4  0x00007fffe9a88e25 in malloc_printerr () from /lib64/libc.so.6
#5  0x00007fffe9a8d724 in malloc () from /lib64/libc.so.6
#6  0x00007fffe9c1c3ac in operator new(unsigned long) () from /lib64/libstdc++.so.6
#7  0x00007fffefeec2b9 in QObject::QObject (this=0x7ffe6c0187e8, parent=0x0)
    at /qt5/qtbase/src/corelib/kernel/qobject.cpp:923
#8  0x00007fffeff52c86 in QDeviceClosedNotifier::QDeviceClosedNotifier (this=0x7ffe6c0187e8)
    at ../../include/QtCore/5.15.14/QtCore/private/../../../../../../../qt5/qtbase/src/corelib/serialization/qtextstream_p.h:68
#9  QTextStreamPrivate::QTextStreamPrivate (q_ptr=0x7fff1c10add0, this=0x7ffe6c0187e0)
    at /qt5/qtbase/src/corelib/serialization/qtextstream.cpp:333
#10 QTextStream::QTextStream (this=0x7fff1c10add0, string=0x7ffe5effc860, openMode=...)
    at /qt5/qtbase/src/corelib/serialization/qtextstream.cpp:1056
#11 0x00007fffea1f5d13 in QDebug::Stream::Stream (string=0x7ffe5effc860, this=0x7fff1c10add0)
    at /home/ksuprynowicz/overte-files/qt/qt5-install/include/QtCore/qdebug.h:76
#12 QDebug::QDebug (string=0x7ffe5effc860, this=0x7ffe5effc868)
    at /home/ksuprynowicz/overte-files/qt/qt5-install/include/QtCore/qdebug.h:115
```

**Comment by ksuprynowicz** [comment]
```
Thread 169 "js:Entities 4" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffe93fff6c0 (LWP 117118)]
0x00007ffff76e7816 in std::_Hashtable<EntityItemID, std::pair<EntityItemID const, std::shared_ptr<render::entities::EntityRenderer> >, std::allocator<std::pair<EntityItemID const, std::shared_ptr<render::entities::EntityRenderer> > >, std::__detail::_Select1st, std::equal_to<EntityItemID>, std::hash<EntityItemID>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_find_before_node (this=this@entry=0x555569068100, __n=1342, __k=..., 
    __code=1758155995) at /usr/include/c++/9/bits/hashtable.h:1577
warning: 1577	/usr/include/c++/9/bits/hashtable.h: No such file or directory
Missing debuginfo, try: dnf debuginfo-install mesa-libGL-24.2.7-100.bazzite.1.fc41.x86_64
Missing debuginfo, try: dnf debuginfo-install mesa-libglapi-24.2.7-100.bazzite.1.fc41.x86_64
Missing debuginfo, try: dnf debuginfo-install mesa-dri-drivers-24.2.7-100.bazzite.1.fc41.x86_64
(gdb) bt
#0  0x00007ffff76e7816 in std::_Hashtable<EntityItemID, std::pair<EntityItemID const, std::shared_ptr<render::entities::EntityRenderer> >, std::allocator<std::pair<EntityItemID const, std::shared_ptr<render::entities::EntityRenderer> > >, std::__detail::_Select1st, std::equal_to<EntityItemID>, std::hash<EntityItemID>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_find_before_node (this=this@entry=0x555569068100, __n=1342, 
    __k=..., __code=1758155995) at /usr/include/c++/9/bits/hashtable.h:1577
#1  0x00007ffff76d6ef3 in std::_Hashtable<EntityItemID, std::pair<EntityItemID const, std::shared_ptr<render::entities::EntityRenderer> >, std::allocator<std::pair<EntityItemID const, std::shared_ptr<render::entities::EntityRenderer> > >, std::__detail::_Select1st, std::equal_to<EntityItemID>, std::hash<EntityItemID>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_find_node (__c=<optimized out>, __key=..., __bkt=<optimized out>, 
    this=0x555569068100) at /usr/include/c++/9/bits/hashtable.h:687
#2  std::_Hashtable<EntityItemID, std::pair<EntityItemID const, std::shared_ptr<render::entities::EntityRenderer> >, std::allocator<std::pair<EntityItemID const, std::shared_ptr<render::entities::EntityRenderer> > >, std::__detail::_Select1st, std::equal_to<EntityItemID>, std::hash<EntityItemID>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::find (__k=..., this=0x555569068100) at /usr/include/c++/9/bits/hashtable.h:1470
#3  std::unordered_map<EntityItemID, std::shared_ptr<render::entities::EntityRenderer>, std::hash<EntityItemID>, std::equal_to<EntityItemID>, std::allocator<std::pair<EntityItemID const, std::shared_ptr<render::entities::EntityRenderer> > > >::find (__x=..., this=0x555569068100) at /usr/include/c++/9/bits/unordered_map.h:926
#4  EntityTreeRenderer::renderableForEntityId (this=0x555569067dc0, id=...)
    at /home/ksuprynowicz/Overte/source/libraries/entities-renderer/src/EntityTreeRenderer.cpp:146
#5  0x00007ffff76f4b5a in <lambda(const EntityItemID&)>::operator() (__closure=<optimized out>, 
    changedEntity=...)
--Type <RET> for more, q to quit, c to continue without paging--c
    at /home/ksuprynowicz/Overte/source/libraries/entities-renderer/src/RenderableEntityItem.cpp:601
#6  std::_Function_handler<void(const EntityItemID&), render::entities::EntityRenderer::onAddToScene(const EntityItemPointer&)::<lambda(const EntityItemID&)> >::_M_invoke(const std::_Any_data &, const EntityItemID &) (
    __functor=..., __args#0=...) at /usr/include/c++/9/bits/std_function.h:300
#7  0x00007ffff7423237 in std::function<void(EntityItemID const&)>::operator() (__args#0=..., 
    this=<optimized out>) at /usr/include/c++/9/bits/std_function.h:688
#8  <lambda()>::operator() (__closure=<optimized out>, __closure=<optimized out>)
    at /home/ksuprynowicz/Overte/build/libraries/entities/src/EntityItem.cpp:3045
#9  ReadWriteLockable::withReadLock<EntityItem::somethingChangedNotification()::<lambda()> > (f=..., 
    this=0x7ffe5c63dab1)
    at /home/ksuprynowicz/Overte/source/libraries/shared/src/shared/ReadWriteLockable.h:109
#10 EntityItem::somethingChangedNotification (this=this@entry=0x7ffe5c63d860)
    at /home/ksuprynowicz/Overte/build/libraries/entities/src/EntityItem.cpp:3043
#11 0x00007ffff743054e in EntityItem::locationChanged (this=0x7ffe5c63d860, tellPhysics=<optimized out>, 
    tellChildren=<optimized out>)
    at /home/ksuprynowicz/Overte/build/libraries/entities/src/EntityItem.cpp:2650
#12 0x00007fffeb72f79c in <lambda(SpatiallyNestablePointer)>::operator() (__closure=<optimized out>, 
    __closure=<optimized out>, object=...)
    at /home/ksuprynowicz/Overte/source/libraries/shared/src/SpatiallyNestable.cpp:1131
#13 std::_Function_handler<void(const std::shared_ptr<SpatiallyNestable>&), SpatiallyNestable::locationChanged(bool, bool)::<lambda(SpatiallyNestablePointer)> >::_M_invoke(const std::_Any_data &, const std::shared_ptr<SpatiallyNestable> &) (__functor=..., __args#0=...) at /usr/include/c++/9/bits/std_function.h:300
#14 0x00007fffeb7353e0 in std::function<void(std::shared_ptr<SpatiallyNestable> const&)>::operator() (
    __args#0=..., this=0x7ffe93ffd6c0) at /usr/include/c++/9/bits/std_function.h:688
#15 SpatiallyNestable::forEachChild (this=<optimized out>, actor=...)
    at /home/ksuprynowicz/Overte/source/libraries/shared/src/SpatiallyNestable.cpp:1081
#16 0x00007fffeb7357d9 in SpatiallyNestable::locationChanged (this=<optimized out>, 
    tellPhysics=<optimized out>, tellChildren=<optimized out>)
    at /home/ksuprynowicz/Overte/source/libraries/shared/src/SpatiallyNestable.cpp:1130
#17 0x00007fffeb72e16e in SpatiallyNestable::setWorldOrientation (this=0x555568fd7020, orientation=..., 
    success=@0x7ffe93ffd7e7: true, tellPhysics=<optimized out>)
    at /home/ksuprynowicz/Overte/source/libraries/shared/src/SpatiallyNestable.cpp:615
#18 0x00007fffeb72a01b in SpatiallyNestable::setWorldOrientation (this=<optimized out>, orientation=...)
    at /home/ksuprynowicz/Overte/source/libraries/shared/src/SpatiallyNestable.cpp:621
#19 0x00007ffff7f73bbf in Avatar::setOrientationViaScript (this=0x555568fd7010, orientation=...)
    at /home/ksuprynowicz/Overte/source/libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp:1750
#20 0x00007ffff7919035 in AvatarData::qt_static_metacall (_o=_o@entry=0x555568fd7010, 
    _c=_c@entry=QMetaObject::WriteProperty, _id=_id@entry=7, _a=_a@entry=0x7ffe93ffd9d0)
    at /home/ksuprynowicz/Overte/build/libraries/avatars/avatars_autogen/UVLADIE3JM/moc_AvatarData.cpp:688
#21 0x00007ffff791a66b in AvatarData::qt_metacall (this=this@entry=0x555568fd7010, 
    _c=_c@entry=QMetaObject::WriteProperty, _id=7, _a=_a@entry=0x7ffe93ffd9d0)
    at /home/ksuprynowicz/Overte/build/libraries/avatars/avatars_autogen/UVLADIE3JM/moc_AvatarData.cpp:759
#22 0x00007ffff7f6d90a in Avatar::qt_metacall (this=this@entry=0x555568fd7010, 
    _c=_c@entry=QMetaObject::WriteProperty, _id=<optimized out>, _a=_a@entry=0x7ffe93ffd9d0)
    at /home/ksuprynowicz/Overte/build/libraries/avatars-renderer/avatars-renderer_autogen/UWUTRV3G23/moc_Avatar.cpp:466
#23 0x000055555581e63a in MyAvatar::qt_metacall (this=0x555568fd7010, _c=QMetaObject::WriteProperty, 
    _id=<optimized out>, _a=0x7ffe93ffd9d0)
    at /home/ksuprynowicz/Overte/build/interface/interface_autogen/HATOO4OGEK/moc_MyAvatar.cpp:1899
#24 0x00007fffefec426b in QMetaProperty::write (this=this@entry=0x7ffe93ffdb00, 
    object=object@entry=0x555568fd7010, value=...) at /qt5/qtbase/src/corelib/kernel/qmetaobject.cpp:3287
#25 0x00007fffeb58b717 in ScriptObjectV8Proxy::setProperty (this=this@entry=0x7ffe8c004960, object=..., 
    name=..., id=<optimized out>, value=...)
    at /home/ksuprynowicz/Overte/source/libraries/script-engine/src/v8/ScriptObjectV8Proxy.cpp:730
#26 0x00007fffeb58bd29 in ScriptObjectV8Proxy::v8Set (name=..., name@entry=..., value=..., value@entry=..., 
    info=...) at /home/ksuprynowicz/Overte/source/libraries/script-engine/src/v8/ScriptObjectV8Proxy.cpp:552
#27 0x00007fffdc361851 in v8::internal::PropertyCallbackArguments::CallNamedSetter (value=..., name=..., 
    interceptor=..., this=0x7ffe93ffdd70) at ../deps/v8/include/v8-local-handle.h:317
#28 v8::internal::(anonymous namespace)::SetPropertyWithInterceptorInternal (value=..., should_throw=..., 
    interceptor=..., it=0x7ffe93ffdf20) at ../deps/v8/src/objects/js-objects.cc:1301
#29 v8::internal::JSObject::SetPropertyWithInterceptor (it=it@entry=0x7ffe93ffdf20, should_throw=..., 
    should_throw@entry=..., value=value@entry=...) at ../deps/v8/src/objects/js-objects.cc:3368
#30 0x00007fffdc3cd4be in v8::internal::Object::SetPropertyInternal (it=it@entry=0x7ffe93ffdf20, value=..., 
    should_throw=..., store_origin=store_origin@entry=v8::internal::StoreOrigin::kNamed, 
    found=found@entry=0x7ffe93ffde87) at ../deps/v8/src/objects/objects.cc:2513
#31 0x00007fffdc3cd745 in v8::internal::Object::SetProperty (it=0x7ffe93ffdf20, value=value@entry=..., 
    store_origin=v8::internal::StoreOrigin::kNamed, should_throw=...)
    at ../deps/v8/src/objects/objects.cc:2631
#32 0x00007fffdc1cfc23 in v8::internal::StoreIC::Store (this=this@entry=0x7ffe93ffdfe0, 
    object=object@entry=..., name=name@entry=..., value=value@entry=..., 
    store_origin=store_origin@entry=v8::internal::StoreOrigin::kNamed) at ../deps/v8/src/ic/ic.cc:1908
#33 0x00007fffdc1d060e in v8::internal::__RT_impl_Runtime_StoreIC_Miss (isolate=0x55557b514220, args=...)
    at ../deps/v8/src/ic/ic.cc:2855
#34 v8::internal::Runtime_StoreIC_Miss (args_length=<optimized out>, args_object=0x7ffe93ffe110, 
    isolate=0x55557b514220) at ../deps/v8/src/ic/ic.cc:2828
#35 0x00007fffdbaafff9 in Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit ()
   from /var/home/starblob/AppImages/squashfs-root/overte/interface/../libraries/script-engine/../../../usr/lib64/libnode.so.108
#36 0x00007fffdbb44502 in Builtins_SetNamedPropertyHandler ()
   from /var/home/starblob/AppImages/squashfs-root/overte/interface/../libraries/script-engine/../../../usr/lib64/libnode.so.108
#37 0x00007fffdba34010 in Builtins_InterpreterEntryTrampoline ()
   from /var/home/starblob/AppImages/squashfs-root/overte/interface/../libraries/script-engine/../../../usr/lib64/libnode.so.108
#38 0x0000143f6f647bc1 in ?? ()
#39 0x0000211a2728a899 in ?? ()
#40 0x0000038ceb6b0209 in ?? ()
#41 0x0000211a2728a779 in ?? ()
#42 0x0000006400000000 in ?? ()
#43 0x000024525356ca01 in ?? ()
#44 0x0000000000000001 in ?? ()
#45 0x0000313585f41ac1 in ?? ()
#46 0x0000313585f44271 in ?? ()
#47 0x00007ffe93ffe1b8 in ?? ()
#48 0x00007fffdba3261c in Builtins_JSEntryTrampoline ()
   from /var/home/starblob/AppImages/squashfs-root/overte/interface/../libraries/script-engine/../../../usr/lib64/libnode.so.108
#49 0x0000288d9b441131 in ?? ()
#50 0x0000313585f41ac1 in ?? ()
#51 0x0000000000000026 in ?? ()
#52 0x00007ffe93ffe220 in ?? ()
#53 0x00007fffdba32343 in Builtins_JSEntry ()
   from /var/home/starblob/AppImages/squashfs-root/overte/interface/../libraries/script-engine/../../../usr/lib64/libnode.so.108
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```
