### ISSUE TITLE
broken (?) glTF model crashes Interface

### ISSUE THREAD

**Issue by JulianGro** [overte-org/overte#239]
Currently ReadyPlayerMe models seem to be damaged in some way, which crashes Interface.

Here is an example file: 
[635d84711260644e7e393e0b.glb.zip](https://github.com/overte-org/overte/files/9894517/635d84711260644e7e393e0b.glb.zip)

The [glTF validator](https://github.khronos.org/glTF-Validator/) shows an error which makes me think that the model is broken in some way.
```json
"code": "ACCESSOR_VECTOR3_NON_UNIT",
"message": "Vector3 at accessor indices 792..794 is not of unit length: 0.7181633880296953.",
"severity": 0,
"pointer": "/meshes/8/primitives/0/attributes/NORMAL"
```

**Comment by daleglass** [comment]
Backtrace:

```
0x00007ffff448cae9 in GLTFSerializer::buildGeometry (this=<optimized out>, hfmModel=..., mapping=..., url=...) at /usr/include/qt5/QtCore/qarraydata.h:62
62	       return reinterpret_cast<void *> (reinterpret_cast<uintptr_t>(this) + offset);
(gdb) bt
#0  0x00007ffff448cae9 in GLTFSerializer::buildGeometry (this=<optimized out>, hfmModel=..., mapping=..., url=...) at /usr/include/qt5/QtCore/qarraydata.h:62
#1  0x00007ffff44914b1 in GLTFSerializer::read (this=0x7ffa54209670, data=..., mapping=..., url=...)
    at /home/dale/git/vircadia/overte-master/libraries/model-serializers/src/GLTFSerializer.cpp:1708
#2  0x00007ffff623f4b1 in ModelLoader::load (this=this@entry=0x2c97c15c, data=..., mapping=..., url=..., webMediaType="model/gltf-binary")
    at /home/dale/git/vircadia/overte-master/libraries/model-networking/src/model-networking/ModelLoader.cpp:23
#3  0x00007ffff62323c3 in GeometryReader::run (this=0x2c97c150)
    at /home/dale/git/vircadia/overte-master/libraries/model-networking/src/model-networking/ModelCache.cpp:158
#4  0x00007ffff3ceb4f2 in QThreadPoolThread::run (this=0x15d844d0) at thread/qthreadpool.cpp:100
#5  0x00007ffff3ce8487 in QThreadPrivate::start (arg=0x15d844d0) at thread/qthread_unix.cpp:330
#6  0x00007fffef6af14d in start_thread (arg=<optimized out>) at pthread_create.c:442
#7  0x00007fffef730950 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```

**Comment by Morgenstern29** [comment]
[dude.zip](https://github.com/overte-org/overte/files/10078179/dude.zip)
I downloaded a sample avatar which was causing a crash. I tried to download it from my server but got the same result.

**Comment by JulianGro** [comment]
That dude.glb doesn't throw any errors. Just some seemingly small warnings:
```json
{
    "uri": "dude.glb",
    "mimeType": "model/gltf-binary",
    "validatorVersion": "2.0.0-dev.3.8",
    "validatedAt": "2022-11-26T12:42:17.423Z",
    "issues": {
        "numErrors": 0,
        "numWarnings": 10,
        "numInfos": 0,
        "numHints": 0,
        "messages": [
            {
                "code": "NODE_SKINNED_MESH_NON_ROOT",
                "message": "Node with a skinned mesh is not root. Parent transforms will not affect a skinned mesh.",
                "severity": 1,
                "pointer": "/nodes/67"
            },
            {
                "code": "NODE_SKINNED_MESH_NON_ROOT",
                "message": "Node with a skinned mesh is not root. Parent transforms will not affect a skinned mesh.",
                "severity": 1,
                "pointer": "/nodes/68"
            },
            {
                "code": "NODE_SKINNED_MESH_NON_ROOT",
                "message": "Node with a skinned mesh is not root. Parent transforms will not affect a skinned mesh.",
                "severity": 1,
                "pointer": "/nodes/69"
            },
            {
                "code": "NODE_SKINNED_MESH_NON_ROOT",
                "message": "Node with a skinned mesh is not root. Parent transforms will not affect a skinned mesh.",
                "severity": 1,
                "pointer": "/nodes/70"
            },
            {
                "code": "NODE_SKINNED_MESH_NON_ROOT",
                "message": "Node with a skinned mesh is not root. Parent transforms will not affect a skinned mesh.",
                "severity": 1,
                "pointer": "/nodes/72"
            },
            {
                "code": "NODE_SKINNED_MESH_NON_ROOT",
                "message": "Node with a skinned mesh is not root. Parent transforms will not affect a skinned mesh.",
                "severity": 1,
                "pointer": "/nodes/73"
            },
            {
                "code": "NODE_SKINNED_MESH_NON_ROOT",
                "message": "Node with a skinned mesh is not root. Parent transforms will not affect a skinned mesh.",
                "severity": 1,
                "pointer": "/nodes/74"
            },
            {
                "code": "NODE_SKINNED_MESH_NON_ROOT",
                "message": "Node with a skinned mesh is not root. Parent transforms will not affect a skinned mesh.",
                "severity": 1,
                "pointer": "/nodes/75"
            },
            {
                "code": "NODE_SKINNED_MESH_NON_ROOT",
                "message": "Node with a skinned mesh is not root. Parent transforms will not affect a skinned mesh.",
                "severity": 1,
                "pointer": "/nodes/76"
            },
            {
                "code": "NODE_SKINNED_MESH_NON_ROOT",
                "message": "Node with a skinned mesh is not root. Parent transforms will not affect a skinned mesh.",
                "severity": 1,
                "pointer": "/nodes/77"
            }
        ],
        "truncated": false
    },
```

**Comment by daleglass** [comment]
PR #263 fixed the crash, but the code remains broken.

The PR added a test for the glTF code, which runs through user-provided models and official Khronos samples. This seems to have narrowed the issue down. The following two samples fail:

https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Fox
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/RecursiveSkeletons

The last one is particularly interesting:

> This model demonstrates tow things:
>
> * Reusing the same mesh multiple times by multiple skins.
> * Binding multiple skins to a single skeleton.
>
> Each skin attaches the same mesh to different lengths of the skeletons, so we have 21 skins bound to multiple lengths of each skeleton.
>
> Using skinning in this way might be seen by some as abusing the glTF format, but it's actually very useful in some circumstances, and can be used by game engines as a stress test on how to handle uncommon, -but valid- skinned meshes.

And is very likely the actual issue that needs fixing. Help from people familiar with rendering engines and  glTF would be extremely appreciated here.

**Comment by AnotherFoxGuy** [comment]
I've ran into this bug today, it seems to happen with every model that [glTFast](https://github.com/atteneder/glTFast) exports

Models that don't crash the interface are looking like this:
![interface_2023-08-29_18-22-55](https://github.com/overte-org/overte/assets/9480940/9da62211-b888-4bad-b0e0-e203291ac402)

**Comment by Morgenstern29** [comment]
> I've ran into this bug today, it seems to happen with every model that [glTFast](https://github.com/atteneder/glTFast) exports
> 
> Models that don't crash the interface are looking like this: ![interface_2023-08-29_18-22-55](https://user-images.githubusercontent.com/9480940/264100740-9da62211-b888-4bad-b0e0-e203291ac402.png)

Yep, indeed, it is how RPM avatars looks in Vircadia if you just use avatar out of the box. You need to convert it in Blender to glb before uploading. Now Vircadia doesn't crash but RPM avatars still not work properly.

**Comment by ksuprynowicz** [comment]
Fixed by https://github.com/overte-org/overte/pull/835
