### ISSUE TITLE
[v8] fox essentials' entity spawner doesn't work

### ISSUE THREAD

**Issue by JulianGro** [overte-org/overte#370]
Trying to spawn an entity like Vulpie using foxEssentials doesn't work in the current v8 branch.
The script is available here: https://scripts.cutelab.space/foxEssentials/foxEssentials.js

**Comment by ksuprynowicz** [comment]
It works now :)

**Comment by JulianGro** [comment]
Still doesn't work for me. Are you sure that you didn't mix this issue up with something else?

**Comment by JulianGro** [comment]
Now that I am running it in KDevelop:
```log
[04/22 21:26:05] [DEBUG] [overte.scriptengine.v8]  Backtrace: ("https://scripts.cutelab.space/foxEssentials/foxEssentials.js spawnEntity:48", "https://scripts.cutelab.space/foxEssentials/foxEssentials.js :67", "https://scripts.cutelab.space/foxEssentials/foxEssentials.js spawnEntityJSON:66", "https://scripts.cutelab.space/foxEssentials/foxEssentials.js webEventReceived:367")
[04/22 21:26:05] [DEBUG] [overte.scriptengine] Signal proxy  "TabletProxy::webEventReceived"  connection call failed: " "failed on line 48 column 40 with message: \"Uncaught Error: Native call of Vec3::sum failed: Cannot convert parameter 1 from undefined to glm::vec3\" backtrace: Error: Native call of Vec3::sum failed: Cannot convert parameter 1 from undefined to glm::vec3\n    at spawnEntity (https://scripts.cutelab.space/foxEssentials/foxEssentials.js:48:41)\n    at https://scripts.cutelab.space/foxEssentials/foxEssentials.js:67:3\n    at Array.forEach (<anonymous>)\n    at spawnEntityJSON (https://scripts.cutelab.space/foxEssentials/foxEssentials.js:66:7)\n    at webEventReceived (https://scripts.cutelab.space/foxEssentials/foxEssentials.js:367:4)" 
[04/22 21:26:05] [DEBUG] [overte.scriptengine] This provided:  false
[04/22 21:26:05] [DEBUG] [overte.scriptengine.v8] Emitting exception: Exception: "Uncaught Error: Native call of Vec3::sum failed: Cannot convert parameter 1 from undefined to glm::vec3" "[Error in signal proxy]"  at line  48 , column  40 Backtrace: ("Error: Native call of Vec3::sum failed: Cannot convert parameter 1 from undefined to glm::vec3", "    at spawnEntity (https://scripts.cutelab.space/foxEssentials/foxEssentials.js:48:41)", "    at https://scripts.cutelab.space/foxEssentials/foxEssentials.js:67:3", "    at Array.forEach (<anonymous>)", "    at spawnEntityJSON (https://scripts.cutelab.space/foxEssentials/foxEssentials.js:66:7)", "    at webEventReceived (https://scripts.cutelab.space/foxEssentials/foxEssentials.js:367:4)")
[04/22 21:26:05] [WARNING] [overte.scriptengine] run ---------- UNCAUGHT EXCEPTION --------
[04/22 21:26:05] [WARNING] [overte.scriptengine] runInThread Exception: "Uncaught Error: Native call of Vec3::sum failed: Cannot convert parameter 1 from undefined to glm::vec3" "[Error in signal proxy]"  at line  48 , column  40 Backtrace: ("Error: Native call of Vec3::sum failed: Cannot convert parameter 1 from undefined to glm::vec3", "    at spawnEntity (https://scripts.cutelab.space/foxEssentials/foxEssentials.js:48:41)", "    at https://scripts.cutelab.space/foxEssentials/foxEssentials.js:67:3", "    at Array.forEach (<anonymous>)", "    at spawnEntityJSON (https://scripts.cutelab.space/foxEssentials/foxEssentials.js:66:7)", "    at webEventReceived (https://scripts.cutelab.space/foxEssentials/foxEssentials.js:367:4)")
```
