### ISSUE TITLE
VR Grab in Create App in V8 branch is broken

### ISSUE THREAD

**Issue by ksuprynowicz** [overte-org/overte#378]
```
[04/22 21:01:23] [WARNING] [overte.scriptengine] ScriptManager::run ---------- UNCAUGHT EXCEPTION --------
[04/22 21:01:23] [WARNING] [overte.scriptengine] runInThread Exception: "Uncaught Error: Native call of Vec3::subtract failed: Cannot convert parameter 2 from null to glm::vec3" "[Error in signal proxy]"  at line  2641 , column  34 Backtrace: ("Error: Native call of Vec3::subtract failed: Cannot convert parameter 2 from null to glm::vec3", "    at Object.onMove (file:///C:/Users/ksupr/source/overte/overte_v8/cmake-build-relwithdebinfo-visual-studio/interface/RelWithDebInfo/scripts/system/create/entitySelectionTool/entitySelectionTool.js:2641:35)", "    at that.mouseMoveEvent (file:///C:/Users/ksupr/source/overte/overte_v8/cmake-build-relwithdebinfo-visual-studio/interface/RelWithDebInfo/scripts/system/create/entitySelectionTool/entitySelectionTool.js:1672:24)", "    at that.checkControllerMove (file:///C:/Users/ksupr/source/overte/overte_v8/cmake-build-relwithdebinfo-visual-studio/interface/RelWithDebInfo/scripts/system/create/entitySelectionTool/entitySelectionTool.js:1782:26)", "    at file:///C:/Users/ksupr/source/overte/overte_v8/cmake-build-relwithdebinfo-visual-studio/interface/RelWithDebInfo/scripts/system/create/edit.js:1708:26")
[04/22 21:01:23] [DEBUG] [overte.scriptengine.v8] "Native call of Vec3::subtract failed: Cannot convert parameter 2 from null to glm::vec3" 
[04/22 21:01:23] [DEBUG] [overte.scriptengine.v8]  Backtrace: ("file:///C:/Users/ksupr/source/overte/overte_v8/cmake-build-relwithdebinfo-visual-studio/interface/RelWithDebInfo/scripts/system/create/entitySelectionTool/entitySelectionTool.js onMove:2641", "file:///C:/Users/ksupr/source/overte/overte_v8/cmake-build-relwithdebinfo-visual-studio/interface/RelWithDebInfo/scripts/system/create/entitySelectionTool/entitySelectionTool.js that.mouseMoveEvent:1672", "file:///C:/Users/ksupr/source/overte/overte_v8/cmake-build-relwithdebinfo-visual-studio/interface/RelWithDebInfo/scripts/system/create/entitySelectionTool/entitySelectionTool.js that.checkControllerMove:1782", "file:///C:/Users/ksupr/source/overte/overte_v8/cmake-build-relwithdebinfo-visual-studio/interface/RelWithDebInfo/scripts/system/create/edit.js :1708")
[04/22 21:01:23] [DEBUG] [overte.scriptengine] Signal proxy  "ScriptManagerScriptingInterface::update"  connection call failed: " "failed on line 2641 column 34 with message: \"Uncaught Error: Native call of Vec3::subtract failed: Cannot convert parameter 2 from null to glm::vec3\" backtrace: Error: Native call of Vec3::subtract failed: Cannot convert parameter 2 from null to glm::vec3\n    at Object.onMove (file:///C:/Users/ksupr/source/overte/overte_v8/cmake-build-relwithdebinfo-visual-studio/interface/RelWithDebInfo/scripts/system/create/entitySelectionTool/entitySelectionTool.js:2641:35)\n    at that.mouseMoveEvent (file:///C:/Users/ksupr/source/overte/overte_v8/cmake-build-relwithdebinfo-visual-studio/interface/RelWithDebInfo/scripts/system/create/entitySelectionTool/entitySelectionTool.js:1672:24)\n    at that.checkControllerMove (file:///C:/Users/ksupr/source/overte/overte_v8/cmake-build-relwithdebinfo-visual-studio/interface/RelWithDebInfo/scripts/system/create/entitySelectionTool/entitySelectionTool.js:1782:26)\n    at file:///C:/Users/ksupr/source/overte/overte_v8/cmake-build-relwithdebinfo-visual-studio/interface/RelWithDebInfo/scripts/system/create/edit.js:1708:26" 
```

**Comment by ksuprynowicz** [comment]
Fixed!
