### ISSUE TITLE
[v8] doppelganger mirror doesn't work

### ISSUE THREAD

**Issue by JulianGro** [overte-org/overte#408]
```
[05/15 12:39:27] [INFO] [overte.scriptengine] [app-doppleganger.js] Script Engine starting:app-doppleganger.js
ConsoleScriptingInterface[05/15 12:39:27] [CRITICAL] [overte.scriptengine.v8] Parameter  0 in method  DebugDraw :: "drawRays"  is of type QMetaType::UnknownType
[Previous message was repeated 2 times]
[05/15 12:39:27] [DEBUG] [overte.scriptengine] Engine initialized
[05/15 12:39:27] [DEBUG] [overte.scriptengine.module] ScriptManager::require( "./doppleganger.js?version=19937" )
[05/15 12:39:27] [DEBUG] [overte.scriptengine.module] require.fetchModuleSource:  "doppleganger.js" QThread(0x56107a1d2650, name = "js:app-doppleganger.js")
[05/15 12:39:27] [DEBUG] [qml] [FlickableWebViewCore.qml] Web Entity JS message: file:///home/juliangro/git/overte/build/interface/scripts/system/more/more.html 503 Uncaught TypeError: EventBridge.forceHtmlAudioOutputDeviceUpdate is not a function
[05/15 12:39:27] [DEBUG] [qml] [FlickableWebViewCore.qml] Web Entity JS message: file:///home/juliangro/git/overte/build/interface/scripts/system/more/more.html 497 Uncaught TypeError: EventBridge.forceHtmlAudioOutputDeviceUpdate is not a function
[05/15 12:39:27] [DEBUG] [overte.scriptengine.module] "require.instantiateModule: doppleganger.js / 20933 bytes"
[05/15 12:39:27] [DEBUG] [overte.scriptengine.v8] ScriptEngineV8::storeGlobalObjectContents:  95  objects stored
[05/15 12:39:27] [DEBUG] [overte.scriptengine.v8] Closure object members: "[\"module\",\"exports\",\"require\",\"__filename\",\"__dirname\"]"
[05/15 12:39:27] [DEBUG] [overte.scriptengine.v8] Test object members: "[\"test_value\"]"
[05/15 12:39:27] [DEBUG] [overte.scriptengine.v8] Script compilation successful:  "https://more.overte.org/applications/doppelganger-mirror/doppleganger.js?version=19937"
[05/15 12:39:27] [DEBUG] [overte.scriptengine.v8] ScriptEngineV8::evaluateInClosure:  95  objects added to global
[05/15 12:39:27] [DEBUG] [overte.scriptengine.v8] ScriptSignalV8Proxy::connect:  "ScriptManagerScriptingInterface::scriptEnding"  fullName:  "ScriptManagerScriptingInterface::scriptEnding"
[05/15 12:39:27] [DEBUG] [overte.scriptengine.v8] Running script: " "https://more.overte.org/applications/doppelganger-mirror/app-doppleganger.js" "  "failed on line 40 column 20 with message: \"Uncaught Error: Function expected as argument to 'connect'\" backtrace: Error: Function expected as argument to 'connect'\n    at https://more.overte.org/applications/doppelganger-mirror/app-doppleganger.js:40:21"
[05/15 12:39:27] [DEBUG] [overte.scriptengine.v8] Emitting exception: Exception: "Uncaught Error: Function expected as argument to 'connect'" "[script evaluation]"  at line  40 , column  20 Backtrace: ("Error: Function expected as argument to 'connect'", "    at https://more.overte.org/applications/doppelganger-mirror/app-doppleganger.js:40:21")
[05/15 12:39:27] [DEBUG] [overte.scriptengine] Waiting for finish
[05/15 12:39:27] [WARNING] [overte.scriptengine] run ---------- UNCAUGHT EXCEPTION --------
[05/15 12:39:27] [WARNING] [overte.scriptengine] runInThread Exception: "Uncaught Error: Function expected as argument to 'connect'" "[script evaluation]"  at line  40 , column  20 Backtrace: ("Error: Function expected as argument to 'connect'", "    at https://more.overte.org/applications/doppelganger-mirror/app-doppleganger.js:40:21")
[05/15 12:39:27] [WARNING] [default] file:///home/juliangro/git/overte/interface/resources/qml/hifi/toolbars/ToolbarButton.qml:93:5: QML Image: Error transferring http://mpassets.highfidelity.com/41f09ec3-976c-49f2-89fe-2d0e1a2b4a98-v1/icons/tablet-icons/web-i.svg - server replied: Bad Gateway
[Previous message was repeated 1 times]
[05/15 12:39:27] [DEBUG] [hifi.ui] setKeyboardRaised:  DefaultFrame_QMLTYPE_39(0x56103e3fdf00, name = "Frame") , raised:  false , numeric:  false , password:  false
[05/15 12:39:27] [DEBUG] [hifi.interface] No matching url ""
[05/15 12:39:27] [WARNING] [hifi.qml] QUrl("") -1 <Unknown File>: Invalid empty URL
```

**Comment by ksuprynowicz** [comment]
Did you try this version too?
https://github.com/overte-org/community-apps/pull/10
