### ISSUE TITLE
v8 Material Creator App Broken

### ISSUE THREAD

**Issue by vegaslon** [overte-org/overte#433]
Open More APP and install Material Data Creator. On windows  the script will run correctly but trying to create a material will not display correctly.

https://media.discordapp.net/attachments/926048440331407360/1110680778507038820/overte_material_creator.png

When try to apply a red albedo color on the cube here it is not being set.

**Comment by JulianGro** [comment]
Linux debug build output:
```
[05/28 12:45:26] [DEBUG] [overte.scriptengine.v8] Function call failed: " "failed on line 82 column 20 with message: \"Uncaught ReferenceError: updateUser is not defined\" backtrace: ReferenceError: updateUser is not defined\n    at https://hifi-utils.jollysoft.com/HiFiApps/MaddersNameTags/connectionUtils.js:82:21\n    at https://hifi-utils.jollysoft.com/HiFiApps/MaddersNameTags/connectionUtils.js:81:23\n    at https://hifi-utils.jollysoft.com/HiFiApps/MaddersNameTags/connectionUtils.js:39:9\n    at https://hifi-utils.jollysoft.com/HiFiApps/MaddersNameTags/connectionUtils.js:27:9"
[05/28 12:45:26] [WARNING] [overte.scriptengine.v8] JS function call failed
[05/28 12:45:26] [DEBUG] [overte.scriptengine] Signal proxy  "TabletProxy::webEventReceived"  connection call failed: " "failed on line 108 column 17 with message: \"Uncaught ReferenceError: eventObj is not defined\" backtrace: ReferenceError: eventObj is not defined\n    at onMoreAppWebEventReceived (https://more.overte.org/applications/materialDataCreator/appMaterialDataCreator.js:108:18)" 
[05/28 12:45:26] [DEBUG] [overte.scriptengine] This provided:  false
[05/28 12:45:26] [DEBUG] [overte.scriptengine.v8] Emitting exception: Exception: "Uncaught ReferenceError: eventObj is not defined" "[Error in signal proxy]"  at line  108 , column  17 Backtrace: ("ReferenceError: eventObj is not defined", "    at onMoreAppWebEventReceived (https://more.overte.org/applications/materialDataCreator/appMaterialDataCreator.js:108:18)")
[05/28 12:45:26] [DEBUG] [overte.scriptengine] Signal proxy  "TabletProxy::webEventReceived"  connection call failed: " "failed on line 108 column 17 with message: \"Uncaught ReferenceError: eventObj is not defined\" backtrace: ReferenceError: eventObj is not defined\n    at onMoreAppWebEventReceived (https://more.overte.org/applications/materialDataCreator/appMaterialDataCreator.js:108:18)" 
[05/28 12:45:26] [DEBUG] [overte.scriptengine] This provided:  false
[05/28 12:45:26] [DEBUG] [overte.scriptengine.v8] Emitting exception: Exception: "Uncaught ReferenceError: eventObj is not defined" "[Error in signal proxy]"  at line  108 , column  17 Backtrace: ("ReferenceError: eventObj is not defined", "    at onMoreAppWebEventReceived (https://more.overte.org/applications/materialDataCreator/appMaterialDataCreator.js:108:18)")
[05/28 12:45:26] [WARNING] [overte.scriptengine] run ---------- UNCAUGHT EXCEPTION --------
[05/28 12:45:26] [WARNING] [overte.scriptengine] runInThread Exception: "Uncaught ReferenceError: eventObj is not defined" "[Error in signal proxy]"  at line  108 , column  17 Backtrace: ("ReferenceError: eventObj is not defined", "    at onMoreAppWebEventReceived (https://more.overte.org/applications/materialDataCreator/appMaterialDataCreator.js:108:18)")
[05/28 12:45:26] [DEBUG] [overte.scriptengine] Signal proxy  "TabletProxy::webEventReceived"  connection call failed: " "failed on line 108 column 17 with message: \"Uncaught ReferenceError: eventObj is not defined\" backtrace: ReferenceError: eventObj is not defined\n    at onMoreAppWebEventReceived (https://more.overte.org/applications/materialDataCreator/appMaterialDataCreator.js:108:18)" 
[05/28 12:45:26] [DEBUG] [overte.scriptengine] This provided:  false
[05/28 12:45:26] [DEBUG] [overte.scriptengine.v8] Emitting exception: Exception: "Uncaught ReferenceError: eventObj is not defined" "[Error in signal proxy]"  at line  108 , column  17 Backtrace: ("ReferenceError: eventObj is not defined", "    at onMoreAppWebEventReceived (https://more.overte.org/applications/materialDataCreator/appMaterialDataCreator.js:108:18)")
[05/28 12:45:26] [WARNING] [overte.scriptengine] run ---------- UNCAUGHT EXCEPTION --------
[05/28 12:45:26] [WARNING] [overte.scriptengine] runInThread Exception: "Uncaught ReferenceError: eventObj is not defined" "[Error in signal proxy]"  at line  108 , column  17 Backtrace: ("ReferenceError: eventObj is not defined", "    at onMoreAppWebEventReceived (https://more.overte.org/applications/materialDataCreator/appMaterialDataCreator.js:108:18)")
[05/28 12:45:28] [DEBUG] [overte.scriptengine] Signal proxy  "TabletProxy::webEventReceived"  connection call failed: " "failed on line 108 column 17 with message: \"Uncaught ReferenceError: eventObj is not defined\" backtrace: ReferenceError: eventObj is not defined\n    at onMoreAppWebEventReceived (https://more.overte.org/applications/materialDataCreator/appMaterialDataCreator.js:108:18)" 
[05/28 12:45:28] [DEBUG] [overte.scriptengine] This provided:  false
[05/28 12:45:28] [DEBUG] [overte.scriptengine.v8] Emitting exception: Exception: "Uncaught ReferenceError: eventObj is not defined" "[Error in signal proxy]"  at line  108 , column  17 Backtrace: ("ReferenceError: eventObj is not defined", "    at onMoreAppWebEventReceived (https://more.overte.org/applications/materialDataCreator/appMaterialDataCreator.js:108:18)")
[05/28 12:45:28] [WARNING] [overte.scriptengine] run ---------- UNCAUGHT EXCEPTION --------
[05/28 12:45:28] [WARNING] [overte.scriptengine] runInThread Exception: "Uncaught ReferenceError: eventObj is not defined" "[Error in signal proxy]"  at line  108 , column  17 Backtrace: ("ReferenceError: eventObj is not defined", "    at onMoreAppWebEventReceived (https://more.overte.org/applications/materialDataCreator/appMaterialDataCreator.js:108:18)")
```

**Comment by AleziaKurdis** [comment]
Is the output (the generated json) have the albedo value correctly generated ? (if not that would be a probleme with the color picker)
If not, if you generate the material and apply it on any entity, is it still broken?
Do you have the same issue with the Material Assistant in the create app (it used the same kind of color picker)

(I would be surprise that the albedo color get broken on the rendering... but less surprised if the color picker or the communication between the UI and the app get broken)

Another test would be to set an emmisive color and see if you have the same issue.

**Comment by ksuprynowicz** [comment]
It looks like it fails due to variable not being declared in strict mode:
```[05/30 20:15:00] [WARNING] [overte.scriptengine] runInThread Exception: "Uncaught ReferenceError: eventObj is not defined" "[Error in signal proxy]"  at line  108 , column  17 Backtrace: ("ReferenceError: eventObj is not defined", "    at onMoreAppWebEventReceived (https://more.overte.org/applications/materialDataCreator/appMaterialDataCreator.js:108:18)")```

**Comment by AleziaKurdis** [comment]
Clearly a "var" is missing in the onMoreAppWebEventReceived function... eventObj miss  declaration (at the function level only).

**Comment by AleziaKurdis** [comment]
Fixed by PR 24 of the community-app repositiory.

**Comment by AleziaKurdis** [comment]
We can close this Issue.
