### ISSUE TITLE
Model create mode crashes viewer when opening for a second time

### ISSUE THREAD

**Issue by jae1911** [overte-org/overte#536]
Steps to reproduce:
1. Open "create app"
2. Click on "create" -> "model"
3. Enter model URI and do what you need with it
4. Close the "create app"
5. Open "create app" again
6. Click on "create" -> "model"
7. Viewer will crash

Build info:

    Build 2023.07.1-rc2

**Comment by JulianGro** [comment]
Takes a couple of tries but can be reproduced on current master.
Full log: https://bin.linux.pizza/?770297a48b7e595f#EbdDMBWr3Px8dyptqpaooKKziEUuBjp7macCAsp9novp
Backtrace:
```backtrace
#0 0x00007f2f933c0f55 in std::__atomic_base<bool>::store(bool, std::memory_order) (__m=std::memory_order_relaxed, __i=true, this=0x606af835c6709166) at /usr/include/c++/13/bits/atomic_base.h:479
#1 std::atomic<bool>::store(bool, std::memory_order) (__m=std::memory_order_relaxed, __i=true, this=0x606af835c6709166) at /usr/include/c++/13/atomic:104
#2 v8::internal::Isolate::set_was_locker_ever_used() (this=0x606af835c66fbc72) at ../deps/v8/src/execution/isolate.h:1512
#3 v8::Locker::Initialize(v8::Isolate*) (this=this@entry=0x7f2e2f342b00, isolate=0x606af835c66fbc72) at ../deps/v8/src/execution/v8threads.cc:37
#4 0x00007f2fa1965f88 in v8::Locker::Locker(v8::Isolate*) (isolate=<optimized out>, this=0x7f2e2f342b00) at /home/juliangro/overte-files/vcpkg/b73f80c2/installed/x64-linux/include/node/v8-locker.h:114
#5 V8ScriptValueTemplate<v8::Value>::V8ScriptValueTemplate(ScriptEngineV8*, v8::Local<v8::Value>) (this=0x7f2e2f342bd0, engine=<optimized out>, value=...) at /home/juliangro/git/overte/libraries/script-engine/src/v8/V8Types.h:29
#6 0x00007f2fa1970585 in ScriptObjectV8Proxy::v8GetPropertyNames(v8::PropertyCallbackInfo<v8::Array> const&) (info=...) at /home/juliangro/git/overte/libraries/script-engine/src/v8/ScriptObjectV8Proxy.cpp:538
#7 0x00007f2f93669143 in v8::internal::PropertyCallbackArguments::CallPropertyEnumerator(v8::internal::Handle<v8::internal::InterceptorInfo>) (interceptor=..., this=0x7f2e2f342ce0) at ../deps/v8/src/api/api-arguments-inl.h:288
#8 v8::internal::PropertyCallbackArguments::CallNamedEnumerator(v8::internal::Handle<v8::internal::InterceptorInfo>) (interceptor=..., this=0x7f2e2f342ce0) at ../deps/v8/src/api/api-arguments-inl.h:155
#9 v8::internal::KeyAccumulator::CollectInterceptorKeysInternal(v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::Handle<v8::internal::JSObject>, v8::internal::Handle<v8::internal::InterceptorInfo>, v8::internal::KeyAccumulator::IndexedOrNamed) (this=0x7f2e2f342e20, receiver=..., object=..., interceptor=..., type=type@entry=v8::internal::KeyAccumulator::kNamed) at ../deps/v8/src/objects/keys.cc:702
#10 0x00007f2f9366975e in v8::internal::KeyAccumulator::CollectInterceptorKeys(v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::Handle<v8::internal::JSObject>, v8::internal::KeyAccumulator::IndexedOrNamed) (this=<optimized out>, receiver=..., receiver@entry=..., object=..., type=type@entry=v8::internal::KeyAccumulator::kNamed) at ../deps/v8/src/objects/keys.cc:734
#11 0x00007f2f9366be55 in v8::internal::KeyAccumulator::CollectOwnPropertyNames(v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::Handle<v8::internal::JSObject>) (this=this@entry=0x7f2e2f342e20, receiver=..., receiver@entry=..., object=..., object@entry=...) at ../deps/v8/src/objects/keys.cc:1048
#12 0x00007f2f9366c85e in v8::internal::KeyAccumulator::CollectOwnKeys(v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::Handle<v8::internal::JSObject>) (this=this@entry=0x7f2e2f342e20, receiver=receiver@entry=..., object=object@entry=...) at ../deps/v8/src/objects/keys.cc:1136
#13 0x00007f2f9366d5b6 in v8::internal::KeyAccumulator::CollectKeys(v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::Handle<v8::internal::JSReceiver>) (this=this@entry=0x7f2e2f342e20, receiver=..., object=...) at ../deps/v8/src/handles/handles.h:44
#14 0x00007f2f9366d7c1 in v8::internal::FastKeyAccumulator::GetKeysSlow(v8::internal::GetKeysConversion) (this=<optimized out>, keys_conversion=v8::internal::GetKeysConversion::kConvertToString) at ../deps/v8/src/objects/keys.cc:563
#15 0x00007f2f9366ddd7 in v8::internal::KeyAccumulator::GetKeys(v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::KeyCollectionMode, v8::internal::PropertyFilter, v8::internal::GetKeysConversion, bool, bool) (object=..., object@entry=..., mode=mode@entry=v8::internal::KeyCollectionMode::kOwnOnly, filter=filter@entry=v8::internal::ENUMERABLE_STRINGS, keys_conversion=keys_conversion@entry=v8::internal::GetKeysConversion::kConvertToString, is_for_in=<optimized out>, is_for_in@entry=false, skip_indices=skip_indices@entry=false) at ../deps/v8/src/objects/keys.cc:96
#16 0x00007f2f9354c957 in v8::internal::JsonStringifier::SerializeJSReceiverSlow(v8::internal::Handle<v8::internal::JSReceiver>) (this=this@entry=0x7f2e2f343080, object=object@entry=...) at ../deps/v8/src/json/json-stringifier.cc:870
#17 0x00007f2f93548f7f in v8::internal::JsonStringifier::SerializeJSObject(v8::internal::Handle<v8::internal::JSObject>, v8::internal::Handle<v8::internal::Object>) (key=..., object=..., this=0x7f2e2f343080) at ../deps/v8/src/handles/handles.h:133
#18 v8::internal::JsonStringifier::Serialize_<false>(v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) (this=this@entry=0x7f2e2f343080, object=..., object@entry=..., key=..., comma=false) at ../deps/v8/src/json/json-stringifier.cc:599
#19 0x00007f2f93549d75 in v8::internal::JsonStringifier::SerializeObject(v8::internal::Handle<v8::internal::Object>) (obj=..., this=0x7f2e2f343080) at ../deps/v8/src/json/json-stringifier.cc:46
#20 v8::internal::JsonStringifier::Stringify(v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>) (this=this@entry=0x7f2e2f343080, object=..., replacer=..., gap=...) at ../deps/v8/src/json/json-stringifier.cc:232
#21 0x00007f2f93549ddb in v8::internal::JsonStringify(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>) (isolate=isolate@entry=0x55bc27813800, object=object@entry=..., replacer=replacer@entry=..., gap=gap@entry=...) at ../deps/v8/src/json/json-stringifier.cc:145
#22 0x00007f2f9326d3e1 in v8::JSON::Stringify(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::String>) (context=..., json_object=json_object@entry=..., gap=gap@entry=...) at ../deps/v8/src/handles/handles.h:133
#23 0x00007f2fa195beba in ScriptEngineV8::scriptValueDebugDetailsV8(V8ScriptValueTemplate<v8::Value> const&) (this=0x55bc27810490, v8Value=...) at /home/juliangro/git/overte/libraries/script-engine/src/v8/ScriptEngineV8.cpp:1382
#24 0x00007f2fa1972534 in ScriptSignalV8Proxy::connect(ScriptValue, ScriptValue) (this=this@entry=0x7f2e02009b70, arg0=..., arg1=...) at /home/juliangro/git/overte/libraries/script-engine/src/v8/ScriptObjectV8Proxy.cpp:1375
#25 0x00007f2fa18b4c0b in ScriptSignalV8ProxyBase::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) (_o=_o@entry=0x7f2e02009b70, _c=_c@entry=QMetaObject::InvokeMetaMethod, _id=_id@entry=1, _a=_a@entry=0x7f2e2f3435f0) at /home/juliangro/git/overte/build/libraries/script-engine/script-engine_autogen/7A2BUK5VA4/moc_ScriptObjectV8Proxy.cpp:154
#26 0x00007f2fa5cbd5ee in QMetaMethod::invoke(QObject*, Qt::ConnectionType, QGenericReturnArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument) const (this=this@entry=0x7f2e020dd500, object=object@entry=0x7f2e02009b70, connectionType=connectionType@entry=Qt::DirectConnection, returnValue=..., val0=..., val1=..., val2=..., val3=..., val4=..., val5=..., val6=..., val7=..., val8=..., val9=...) at kernel/qmetaobject.cpp:2310
#27 0x00007f2fa1979f7d in QMetaMethod::invoke(QObject*, Qt::ConnectionType, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument) const (val9=..., val8=..., val7=..., val6=..., val5=..., val4=..., val3=..., val2=..., val1=..., val0=..., connectionType=Qt::DirectConnection, object=0x7f2e02009b70, this=0x7f2e020dd500) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qmetaobject.h:122
#28 ScriptMethodV8Proxy::call(v8::FunctionCallbackInfo<v8::Value> const&) (this=this@entry=0x7f2e020574d0, arguments=...) at /home/juliangro/git/overte/libraries/script-engine/src/v8/ScriptObjectV8Proxy.cpp:1079
#29 0x00007f2fa197a611 in ScriptMethodV8Proxy::callback(v8::FunctionCallbackInfo<v8::Value> const&) (arguments=...) at /home/juliangro/git/overte/libraries/script-engine/src/v8/ScriptObjectV8Proxy.cpp:957
#30 0x00007f2f932a83e1 in v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo) (this=this@entry=0x7f2e2f343b00, handler=..., handler@entry=...) at ../deps/v8/src/api/api-arguments-inl.h:147
#31 0x00007f2f932a89c4 in v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) (isolate=isolate@entry=0x55bc27813800, function=..., new_target=..., fun_data=..., receiver=..., args=...) at ../deps/v8/src/builtins/builtins-api.cc:112
#32 0x00007f2f932a927f in v8::internal::Builtin_Impl_HandleApiCall (isolate=0x55bc27813800, args=...) at ../deps/v8/src/builtins/builtins-api.cc:142
#33 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) (args_length=<optimized out>, args_object=0x7f2e2f343c58, isolate=0x55bc27813800) at ../deps/v8/src/builtins/builtins-api.cc:130
#34 0x00007f2f92e073b9 in Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit () at /home/juliangro/overte-files/vcpkg/b73f80c2/installed/x64-linux/lib/libnode.so.108
#35 0x00007f2f92d8b310 in Builtins_InterpreterEntryTrampoline () at /home/juliangro/overte-files/vcpkg/b73f80c2/installed/x64-linux/lib/libnode.so.108
#36 0x00002b56e49015b9 in ()
#37 0x000003deb633d141 in ()
#38 0x0000000600000000 in ()
#39 0x00002b56e4901689 in ()
#40 0x00001eb848484ac1 in ()
#41 0x0000188ee5c41919 in ()
#42 0x00001acc9c603e49 in ()
#43 0x00001eb848483559 in ()
#44 0x00001eb8484834d9 in ()
#45 0x0000188ee5c41919 in ()
#46 0x00001eb848484ac1 in ()
#47 0x000003deb633d141 in ()
#48 0x00001eb848483491 in ()
#49 0x00001eb848483421 in ()
#50 0x00002b56e49015b9 in ()
#51 0x0000012f00000000 in ()
#52 0x000021f7402397a1 in ()
#53 0x0000000000000001 in ()
#54 0x00000b1303b55289 in ()
#55 0x00000b1303b552c9 in ()
#56 0x00007f2e2f343d38 in ()
#57 0x00007f2f92d8b310 in Builtins_InterpreterEntryTrampoline () at /home/juliangro/overte-files/vcpkg/b73f80c2/installed/x64-linux/lib/libnode.so.108
#58 0x00000b1303b545a9 in ()
#59 0x00001eb848483269 in ()
#60 0x00000b1303b545a9 in ()
#61 0x00000b1303b55289 in ()
#62 0x00001eb848483229 in ()
#63 0x00001acc9c604ac9 in ()
#64 0x000000b600000000 in ()
#65 0x00003655fcaa1359 in ()
#66 0x0000000000000002 in ()
#67 0x0000188ee5c41919 in ()
#68 0x0000188ee5c45ff1 in ()
#69 0x00007f2e2f343da8 in ()
#70 0x00007f2fbede9c1f in ()
#71 0x000000c903758101 in ()
#72 0x00001eb8484831f1 in ()
#73 0x00001eb848483339 in ()
#74 0x000000c903758101 in ()
#75 0x0000188ee5c41919 in ()
#76 0x00000632a0201e09 in ()
#77 0x00001eb8484832f9 in ()
#78 0x000021f74023de71 in ()
#79 0x000021f7402302d9 in ()
#80 0x0000000000000004 in ()
#81 0x00001eb848483361 in ()
#82 0x00001eb8484832f9 in ()
#83 0x00007f2e2f343e40 in ()
#84 0x00007f2f92e1f78f in Builtins_ArrayForEach () at /home/juliangro/overte-files/vcpkg/b73f80c2/installed/x64-linux/lib/libnode.so.108
```

**Comment by ksuprynowicz** [comment]
Same thing happens with opening window for adding material second time:
```
[08/19 15:08:30] [DEBUG] [overte.scriptengine.v8] ScriptSignalV8Proxy::connect:  "InteractiveWindow::fromQml"  fullName:  "InteractiveWindow::fromQml"
[08/19 15:08:30] [DEBUG] [overte.scriptengine.v8] ScriptSignalV8Proxy::connect: entry details:  "[object Object] JSON: {}"
[08/19 15:08:30] [DEBUG] [overte.scriptengine.v8] ScriptSignalV8Proxy::connect: entry proxy:  "TabletProxy::fromQml"
terminate called after throwing an instance of 'std::bad_array_new_length'
  what():  std::bad_array_new_length
Signal: SIGABRT (Aborted)
```

```
__pthread_kill_implementation 0x00007ffff12a9d3c
__pthread_kill_internal 0x00007ffff12a9d9f
__GI_raise 0x00007ffff125af32
__GI_abort 0x00007ffff1245472
<unknown> 0x00007fffeda9d919
<unknown> 0x00007fffedaa8e1a
std::terminate() 0x00007fffedaa8e85
__cxa_rethrow 0x00007fffedaa912b
<unknown> 0x00007ffff60927a7
QHash::detach_helper qhash.h:631
QHash::detach qhash.h:291
QHash::begin qhash.h:502
ScriptObjectV8Proxy::getPropertyNames ScriptObjectV8Proxy.cpp:569
ScriptObjectV8Proxy::v8GetPropertyNames ScriptObjectV8Proxy.cpp:539
v8::internal::KeyAccumulator::CollectInterceptorKeysInternal(v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::Handle<v8::internal::JSObject>, v8::internal::Handle<v8::internal::InterceptorInfo>, v8::internal::KeyAccumulator::IndexedOrNamed) 0x00007fffe2f73ae8
v8::internal::KeyAccumulator::CollectOwnKeys(v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::Handle<v8::internal::JSObject>) 0x00007fffe2f77332
v8::internal::KeyAccumulator::CollectKeys(v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::Handle<v8::internal::JSReceiver>) 0x00007fffe2f78798
v8::internal::FastKeyAccumulator::GetKeysSlow(v8::internal::GetKeysConversion) 0x00007fffe2f78963
v8::internal::KeyAccumulator::GetKeys(v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::KeyCollectionMode, v8::internal::PropertyFilter, v8::internal::GetKeysConversion, bool, bool) 0x00007fffe2f77b3c
v8::internal::JsonStringifier::SerializeJSReceiverSlow(v8::internal::Handle<v8::internal::JSReceiver>) 0x00007fffe2e5d90f
v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<false>(v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) 0x00007fffe2e5ecd7
v8::internal::JsonStringifier::Stringify(v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>) 0x00007fffe2e6012e
v8::internal::JsonStringify(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>) 0x00007fffe2e601bc
v8::JSON::Stringify(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::String>) 0x00007fffe2b8d0e1
ScriptEngineV8::scriptValueDebugDetailsV8 ScriptEngineV8.cpp:1401
ScriptSignalV8Proxy::connect ScriptObjectV8Proxy.cpp:1384
ScriptSignalV8ProxyBase::qt_static_metacall moc_ScriptObjectV8Proxy.cpp:154
QMetaMethod::invoke(QObject*, Qt::ConnectionType, QGenericReturnArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument) const 0x00007ffff62bc88e
QMetaMethod::invoke qmetaobject.h:122
ScriptMethodV8Proxy::call ScriptObjectV8Proxy.cpp:1079
ScriptMethodV8Proxy::callback ScriptObjectV8Proxy.cpp:957
v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo) 0x00007fffe2bc6c6a
<unknown> 0x00007fffe2bc7632
v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) 0x00007fffe2bc7b1f
<unknown> 0x00007fffe2a79c79
```

**Comment by JulianGro** [comment]
Same issue happens when creating material entities.

**Comment by ksuprynowicz** [comment]
I added use after delete guard and I found that object proxy gets used after is has been deleted:
```
ScriptEngineV8::getIsolate() ScriptEngineV8.h:188
V8ScriptValueTemplate::V8ScriptValueTemplate(ScriptEngineV8 *, v8::Local<…>) V8Types.h:29
ScriptObjectV8Proxy::v8GetPropertyNames(const v8::PropertyCallbackInfo<…> &) ScriptObjectV8Proxy.cpp:553
ScriptEngineV8::scriptValueDebugDetailsV8(const V8ScriptValueTemplate<…> &) ScriptEngineV8.cpp:1514
ScriptSignalV8Proxy::connect(ScriptValue, ScriptValue) ScriptObjectV8Proxy.cpp:1412
ScriptMethodV8Proxy::call(const v8::FunctionCallbackInfo<…> &) ScriptObjectV8Proxy.cpp:1099
ScriptMethodV8Proxy::callback(const v8::FunctionCallbackInfo<…> &) ScriptObjectV8Proxy.cpp:976
ScriptSignalV8Proxy::qt_metacall(QMetaObject::Call, int, void **) ScriptObjectV8Proxy.cpp:1286
Application::notify(QObject *, QEvent *) Application.cpp:4292
ScriptManager::run() ScriptManager.cpp:1018
operator() ScriptManager.cpp:419
```

**Comment by ksuprynowicz** [comment]
This part looks suspicious, foundIt never gets set, so value can be added several times, but upon disconnect it will be removed only once:
```C++
        bool foundIt = false;
        for (int idx = 0; idx < length && !foundIt; ++idx) {
            v8::Local<v8::Value> entry = destArray->Get(destFunctionContext, idx).ToLocalChecked();
            {
                qCDebug(scriptengine_v8) << "ScriptSignalV8Proxy::connect: entry details: " << _engine->scriptValueDebugDetailsV8(V8ScriptValue(_engine, entry));
                Q_ASSERT(entry->IsObject());
                V8ScriptValue v8EntryObject(_engine, entry);
                Q_ASSERT(ScriptObjectV8Proxy::unwrapProxy(v8EntryObject));
                // For debugging
                ScriptSignalV8Proxy* entryProxy = dynamic_cast<ScriptSignalV8Proxy*>(ScriptObjectV8Proxy::unwrapProxy(v8EntryObject)->toQObject());
                Q_ASSERT(thisProxy);
                qCDebug(scriptengine_v8) << "ScriptSignalV8Proxy::connect: entry proxy: " << entryProxy->fullName();
            }
            if (!newArray->Set(destFunctionContext, idx, entry).FromMaybe(false)) {
                Q_ASSERT(false);
            }
        }
```

**Comment by ksuprynowicz** [comment]
It doesn't seem like access after delete after all, it's very confusing

**Comment by ksuprynowicz** [comment]
Also the signals from the same type of window seem to be adding up, even though those are separate instances, and pprevious instance has been already closed:
```
[05/18 00:46:47] [DEBUG] [overte.scriptengine.v8] ScriptSignalV8Proxy::connect:  "InteractiveWindow::fromQml"  fullName:  "InteractiveWindow::fromQml"
[05/18 00:46:47] [DEBUG] [overte.scriptengine.v8] ScriptSignalV8Proxy::connect: entry details:  "[object Object] JSON: {}"
[05/18 00:46:47] [DEBUG] [overte.scriptengine.v8] ScriptSignalV8Proxy::connect: entry proxy:  "TabletProxy::fromQml"
[05/18 00:46:47] [DEBUG] [overte.scriptengine.v8] ScriptSignalV8Proxy::connect: entry details:  "[object Object] JSON: {}"
[05/18 00:46:47] [DEBUG] [overte.scriptengine.v8] ScriptSignalV8Proxy::connect: entry proxy:  "InteractiveWindow::fromQml"
[05/18 00:46:47] [DEBUG] [overte.scriptengine.v8] ScriptSignalV8Proxy::connect: entry details:  "[object Object] JSON: {}"
[05/18 00:46:47] [DEBUG] [overte.scriptengine.v8] ScriptSignalV8Proxy::connect: entry proxy:  "InteractiveWindow::fromQml"
[05/18 00:46:47] [DEBUG] [overte.scriptengine.v8] ScriptSignalV8Proxy::connect: entry details:  "[object Object] JSON: {}"
[05/18 00:46:47] [DEBUG] [overte.scriptengine.v8] ScriptSignalV8Proxy::connect: entry proxy:  "InteractiveWindow::fromQml"
[05/18 00:46:47] [DEBUG] [overte.scriptengine.v8] ScriptSignalV8Proxy::connect: entry details:  "[object Object] JSON: {}"
[05/18 00:46:47] [DEBUG] [overte.scriptengine.v8] ScriptSignalV8Proxy::connect: entry proxy:  "InteractiveWindow::fromQml"
```

**Comment by ksuprynowicz** [comment]
Something really unexpected is happening there. I added a debug print to check if consecutive windows are using the same signal proxy (which would explain accumulating signals from previous windows).
It turns out they don't, each window has its own signal proxy:
```
ScriptSignalV8ProxyBase(0x7ffbd00d5ee0)
ScriptSignalV8ProxyBase(0x7ffbd0107ee0)
ScriptSignalV8ProxyBase(0x7ffc881f8040)
```
Why then previous signals are available there?

**Comment by ksuprynowicz** [comment]
I was misunderstanding that part of code. It turns out it leaves pointer to signal proxy in connection callbacks, but that doesn't seem to be used anywhere.
