### ISSUE TITLE
Crash when leaving/entering Overte Hub repeatedly without allowing it to fully load

### ISSUE THREAD

**Issue by ksuprynowicz** [overte-org/overte#689]
The message is:

```
[10/30 18:03:39] [DEBUG] [hifi.networking] Server unavailable  - retrying asset load - attempt 3  of  8
[10/30 18:03:39] [DEBUG] [hifi.networking] Retryable error while loading: attempt: 4 attemptsRemaining: 4
[10/30 18:03:39] [DEBUG] [hifi.networking] Server unavailable for - may retry in 16000 ms if resource is still needed
[10/30 18:03:45] [DEBUG] [overte.scriptengine] "Retrying script request [5 / 5]"
[10/30 18:03:45] [DEBUG] [hifi.networking] HTTPResourceRequest error: ContentAccessDenied
[10/30 18:03:45] [WARNING] [overte.scriptengine] Error loading script from URL ( "Error" )
terminate called after throwing an instance of 'std::bad_weak_ptr'
  what():  bad_weak_ptr
```

**Comment by JulianGro** [comment]
```backtrace
*** Program received signal SIGABRT (Aborted) ***(gdb) 30bt
#0 __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44
#1 0x00007f53eaaa815f in __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2 0x00007f53eaa5a472 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3 0x00007f53eaa444b2 in __GI_abort () at ./stdlib/abort.c:79
#4 0x00007f53eaca09db in () at /lib/x86_64-linux-gnu/libstdc++.so.6
#5 0x00007f53eacaffaa in () at /lib/x86_64-linux-gnu/libstdc++.so.6
#6 0x00007f53eacb0015 in () at /lib/x86_64-linux-gnu/libstdc++.so.6
#7 0x00007f53eacb0268 in () at /lib/x86_64-linux-gnu/libstdc++.so.6
#8 0x0000564f4b2c43e1 in std::__throw_bad_weak_ptr() () at /usr/include/c++/13/bits/shared_ptr_base.h:96
#9 0x0000564f4b2e19f5 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count(std::__weak_count<(__gnu_cxx::_Lock_policy)2> const&) (this=0x7ffdd1371968, __r=...) at /usr/include/c++/13/bits/shared_ptr_base.h:1245
#10 0x00007f53ec4263ab in std::__shared_ptr<ScriptManager, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<ScriptManager, void>(std::__weak_ptr<ScriptManager, (__gnu_cxx::_Lock_policy)2> const&) (this=0x7ffdd1371960, __r=...) at /usr/include/c++/13/bits/shared_ptr_base.h:1548
#11 0x00007f53ec424523 in std::shared_ptr<ScriptManager>::shared_ptr<ScriptManager, void>(std::weak_ptr<ScriptManager> const&) (this=0x7ffdd1371960, __r=std::weak_ptr<ScriptManager> (expired, weak count 3) = {...}) at /usr/include/c++/13/bits/shared_ptr.h:381
#12 0x00007f53ec43baec in operator()(QString const&, QString const&, bool, bool, QString const&) const (__closure=0x564f63385be0, url="https://raw.githubusercontent.com/Basinsky/Puzzle/main/PuzzleClient.js?1654977058605", contents="(function() {\n var myID;\n var LOCATION_ROOT_URL = Script.resolvePath(\".\"); \n var hoverSound = SoundCache.getSound(LOCATION_ROOT_URL +\"108336__qat__click-01-fast.wav\");\n var swooshSound ="..., isURL=true, success=true, status="Success") at /home/juliangro/git/overte/libraries/script-engine/src/ScriptManager.cpp:1950
#13 0x00007f53ec4444ed in std::__invoke_impl<void, ScriptManager::loadEntityScript(const EntityItemID&, const QString&, bool)::<lambda(const QString&, const QString&, bool, bool, const QString&)>&, const QString&, const QString&, bool, bool, const QString&>(std::__invoke_other, struct {...} &) (__f=...) at /usr/include/c++/13/bits/invoke.h:61
#14 0x00007f53ec443a27 in std::__invoke_r<void, ScriptManager::loadEntityScript(const EntityItemID&, const QString&, bool)::<lambda(const QString&, const QString&, bool, bool, const QString&)>&, const QString&, const QString&, bool, bool, const QString&>(struct {...} &) (__fn=...) at /usr/include/c++/13/bits/invoke.h:150
#15 0x00007f53ec442ad7 in std::_Function_handler<void(const QString&, const QString&, bool, bool, const QString&), ScriptManager::loadEntityScript(const EntityItemID&, const QString&, bool)::<lambda(const QString&, const QString&, bool, bool, const QString&)> >::_M_invoke(const std::_Any_data &, const QString &, const QString &, bool &&, bool &&, const QString &) (__functor=..., __args#0="https://raw.githubusercontent.com/Basinsky/Puzzle/main/PuzzleClient.js?1654977058605", __args#1="(function() {\n var myID;\n var LOCATION_ROOT_URL = Script.resolvePath(\".\"); \n var hoverSound = SoundCache.getSound(LOCATION_ROOT_URL +\"108336__qat__click-01-fast.wav\");\n var swooshSound ="..., __args#2=@0x7ffdd1371ba4: true, __args#3=@0x7ffdd1371ba0: true, __args#4="Success") at /usr/include/c++/13/bits/std_function.h:290
#16 0x00007f53ec40f32b in std::function<void (QString const&, QString const&, bool, bool, QString const&)>::operator()(QString const&, QString const&, bool, bool, QString const&) const (this=0x7ffdd1371c10, __args#0="https://raw.githubusercontent.com/Basinsky/Puzzle/main/PuzzleClient.js?1654977058605", __args#1="(function() {\n var myID;\n var LOCATION_ROOT_URL = Script.resolvePath(\".\"); \n var hoverSound = SoundCache.getSound(LOCATION_ROOT_URL +\"108336__qat__click-01-fast.wav\");\n var swooshSound ="..., __args#2=true, __args#3=true, __args#4="Success") at /usr/include/c++/13/bits/std_function.h:591
#17 0x00007f53ec40c792 in ScriptCache::scriptContentAvailable(int) (this=0x564f4fce5c10, maxRetries=5) at /home/juliangro/git/overte/libraries/script-engine/src/ScriptCache.cpp:215
#18 0x00007f53ec40a8a4 in operator()() const (__closure=0x7f5340168510) at /home/juliangro/git/overte/libraries/script-engine/src/ScriptCache.cpp:128
#19 0x00007f53ec40d15c in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, ScriptCache::getScriptContents(const QString&, contentAvailableCallback, bool, int)::<lambda()> >::call(struct {...} &, void **) (f=..., arg=0x7f52004c5088) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:146
#20 0x00007f53ec40d067 in QtPrivate::Functor<ScriptCache::getScriptContents(const QString&, contentAvailableCallback, bool, int)::<lambda()>, 0>::call<QtPrivate::List<>, void>(struct {...} &, void *, void **) (f=..., arg=0x7f52004c5088) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:256
#21 0x00007f53ec40cf55 in QtPrivate::QFunctorSlotObject<ScriptCache::getScriptContents(const QString&, contentAvailableCallback, bool, int)::<lambda()>, 0, QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase *, QObject *, void **, bool *) (which=1, this_=0x7f5340168500, r=0x564f4fce5c10, a=0x7f52004c5088, ret=0x0) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:443
#22 0x00007f53f1cf99b0 in QObject::event(QEvent*) (this=0x564f4fce5c10, e=0x7f52004c5040) at kernel/qobject.cpp:1347
#23 0x00007f53ebb62f32 in QApplicationPrivate::notify_helper(QObject*, QEvent*) (this=<optimized out>, receiver=0x564f4fce5c10, e=0x7f52004c5040) at kernel/qapplication.cpp:3640
#24 0x0000564f4b04c559 in Application::notify(QObject*, QEvent*) (this=0x7ffdd1372410, object=0x564f4fce5c10, event=0x7f52004c5040) at /home/juliangro/git/overte/interface/src/Application.cpp:4206
#25 0x00007f53f1ccc7b8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) (receiver=0x564f4fce5c10, event=0x7f52004c5040) at kernel/qcoreapplication.cpp:1064
#26 0x00007f53f1ccc992 in QCoreApplication::sendEvent(QObject*, QEvent*) (receiver=<optimized out>, event=<optimized out>) at kernel/qcoreapplication.cpp:1462
#27 0x00007f53f1ccfec1 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) (receiver=0x0, event_type=0, data=0x564f4d381640) at kernel/qcoreapplication.cpp:1821
#28 0x00007f53f1cd041c in QCoreApplication::sendPostedEvents(QObject*, int) (receiver=<optimized out>, event_type=<optimized out>) at kernel/qcoreapplication.cpp:1680
#29 0x00007f53f1d28707 in postEventSourceDispatch(GSource*, GSourceFunc, gpointer) (s=0x564f4dc04590) at kernel/qeventdispatcher_glib.cpp:277
#30 0x00007f53eb3111b4 in g_main_dispatch (context=context@entry=0x564f4d91ce10) at ../../../glib/gmain.c:3476
#31 0x00007f53eb3142d7 in g_main_context_dispatch_unlocked (context=0x564f4d91ce10) at ../../../glib/gmain.c:4284
#32 g_main_context_iterate_unlocked (context=context@entry=0x564f4d91ce10, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../../../glib/gmain.c:4349
#33 0x00007f53eb3148f0 in g_main_context_iteration (context=0x564f4d91ce10, may_block=1) at ../../../glib/gmain.c:4414
#34 0x00007f53f1d27dba in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (this=0x564f4db9d670, flags=...) at kernel/qeventdispatcher_glib.cpp:423
#35 0x00007f53f1ccb16b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) (this=this@entry=0x7ffdd1372350, flags=..., flags@entry=...) at ../../include/QtCore/../../src/corelib/global/qflags.h:69
#36 0x00007f53f1cd3914 in QCoreApplication::exec() () at ../../include/QtCore/../../src/corelib/global/qflags.h:121
#37 0x0000564f4b34e5d0 in main(int, char const**) (argc=2, argv=0x7ffdd1375f18) at /home/juliangro/git/overte/interface/src/main.cpp:667
30^done
```
