### ISSUE TITLE
nametags.js sometimes spams the log

### ISSUE THREAD

**Issue by daleglass** [overte-org/overte#787]
There's a constant stream of this on the console. It comes out as a huge flood of hundreds of lines per second, and likely impacts performance.

```
[01/14 12:53:06] [DEBUG] [hifi.shared] Warning -- getWorldVelocity failed QUuid("{88c9e628-71f1-4969-b06b-7ad49415109d}")
[01/14 12:53:06] [DEBUG] [hifi.shared] Warning -- getAngularVelocity failed QUuid("{88c9e628-71f1-4969-b06b-7ad49415109d}")
[01/14 12:53:06] [DEBUG] [hifi.shared] getQueryAACube failed for QUuid("{88c9e628-71f1-4969-b06b-7ad49415109d}")
```

The object IDs are nowhere to be seen. It looks like nametags.js is to blame for this, because it goes away after reloading it.

**Comment by daleglass** [comment]
Another message:

```
[01/28 00:33:21] [DEBUG] [hifi.shared] Warning -- getWorldVelocity failed QUuid("{b349e69a-922e-4673-85a6-0e323889ad13}")
[01/28 00:33:21] [DEBUG] [hifi.shared] Warning -- getAngularVelocity failed QUuid("{b349e69a-922e-4673-85a6-0e323889ad13}")
[01/28 00:33:21] [DEBUG] [hifi.shared] Warning -- getWorldVelocity failed QUuid("{5145fbf2-8bcf-4378-bfee-13b5511ffb16}")
[01/28 00:33:21] [DEBUG] [hifi.shared] Warning -- getAngularVelocity failed QUuid("{5145fbf2-8bcf-4378-bfee-13b5511ffb16}")
[01/28 00:33:21] [DEBUG] [hifi.render] Item could not be rendered with invalid key [ShapeKey: INVALID] 
[01/28 00:33:21] [CRITICAL] [overte.scriptengine] [nametags.js] Function call failed: "failed on line 117 column 59 with message: "Uncaught TypeError: Cannot read properties of undefined (reading 'overlay')" backtrace: TypeError: Cannot read properties of undefined (reading 'overlay')
[01/28 00:33:21] [CRITICAL] [overte.scriptengine]     at Function.<anonymous> (https://more.overte.org/applications/nametags/nametags.js:117:60)
[01/28 00:33:21] [CRITICAL] [overte.scriptengine] [nametags.js] JS function call failed: 
[01/28 00:33:21] [CRITICAL] [overte.scriptengine] [nametags.js] Function call failed: "failed on line 117 column 59 with message: "Uncaught TypeError: Cannot read properties of undefined (reading 'overlay')" backtrace: TypeError: Cannot read properties of undefined (reading 'overlay')
[01/28 00:33:21] [CRITICAL] [overte.scriptengine]     at Function.<anonymous> (https://more.overte.org/applications/nametags/nametags.js:117:60)
[01/28 00:33:21] [CRITICAL] [overte.scriptengine] [nametags.js] JS function call failed: 
[01/28 00:33:21] [CRITICAL] [overte.scriptengine] [nametags.js] Function call failed: "failed on line 117 column 59 with message: "Uncaught TypeError: Cannot read properties of undefined (reading 'overlay')" backtrace: TypeError: Cannot read properties of undefined (reading 'overlay')
[01/28 00:33:21] [CRITICAL] [overte.scriptengine]     at Function.<anonymous> (https://more.overte.org/applications/nametags/nametags.js:117:60)
[01/28 00:33:21] [CRITICAL] [overte.scriptengine] [nametags.js] JS function call failed: 
[01/28 00:33:21] [CRITICAL] [overte.scriptengine] [nametags.js] Function call failed: "failed on line 117 column 59 with message: "Uncaught TypeError: Cannot read properties of undefined (reading 'overlay')" backtrace: TypeError: Cannot read properties of undefined (reading 'overlay')
[01/28 00:33:21] [CRITICAL] [overte.scriptengine]     at Function.<anonymous> (https://more.overte.org/applications/nametags/nametags.js:117:60)
```

Repeats a whole bunch of times, then stops.
