### ISSUE TITLE
OpenGL errors

### ISSUE THREAD

**Issue by daleglass** [overte-org/overte#999]
In debug mode, these pop up during startup:

```
[06/04 23:51:48] [WARNING] [qt.qpa.wayland] Wayland does not support QWindow::requestActivate()
[06/04 23:51:48] [WARNING] [hifi.gpu.gl45] OpenGL error 1280 in glGetIntegerv
[06/04 23:51:48] [WARNING] [hifi.gpu.gl45] OpenGL error 1282 in glTextureParameteri
[Previous message was repeated 5 times]
[06/04 23:51:48] [WARNING] [hifi.gpu.gl45] OpenGL error 1282 in glTextureParameterf
[06/04 23:51:48] [WARNING] [hifi.gpu.gl45] OpenGL error 1280 in glTextureParameterfv
[06/04 23:51:48] [WARNING] [hifi.gpu.gl45] OpenGL error 1282 in glTextureParameterf
[Previous message was repeated 3 times]
[06/04 23:51:48] [WARNING] [hifi.gpu.gl45] OpenGL error 1282 in glTextureParameteri
[Previous message was repeated 5 times]
[06/04 23:51:48] [WARNING] [hifi.gpu.gl45] OpenGL error 1282 in glTextureParameterf
[06/04 23:51:48] [WARNING] [hifi.gpu.gl45] OpenGL error 1280 in glTextureParameterfv
[06/04 23:51:48] [WARNING] [hifi.gpu.gl45] OpenGL error 1282 in glTextureParameterf
```

The `glGetIntegerv` is probably dynamic memory allocation not working on Intel Arc, but the rest are probably more interesting.

**Comment by daleglass** [comment]
Most seem to be coming from here:
```
[06/05 23:24:28] [WARNING] [hifi.gpu.gl45] OpenGL error 1282 in glTextureParameteri

Thread 58 "Presentation Th" received signal SIGINT, Interrupt.
__pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=2, no_tid=no_tid@entry=0) at pthread_kill.c:44
44	     return INTERNAL_SYSCALL_ERROR_P (ret) ? INTERNAL_SYSCALL_ERRNO (ret) : 0;
(gdb) bt
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=2, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007fffe32ab1b3 in __pthread_kill_internal (threadid=<optimized out>, signo=2) at pthread_kill.c:78
#2  0x00007fffe325365e in __GI_raise (sig=2) at ../sysdeps/posix/raise.c:26
#3  0x00007ffff2b31fd1 in LogHandler::printMessage (this=0x7ffff2bfee00 <LogHandler::getInstance()::staticInstance>, type=type@entry=LogWarning, context=..., message=...) at /home/dale/git/overte/libraries/shared/src/LogHandler.cpp:333
#4  0x0000000000738191 in messageHandler (type=QtWarningMsg, context=..., message=...) at /home/dale/git/overte/interface/src/Application.cpp:580
#5  0x00007ffff6ae7a30 in qt_message_print (msgType=msgType@entry=QtWarningMsg, context=..., message=...) at global/qlogging.cpp:1848
#6  0x00007ffff6ae90e4 in qt_message_output (msgType=QtWarningMsg, context=..., message=...) at global/qlogging.cpp:1929
#7  0x00007ffff6be6420 in QDebug::~QDebug (this=this@entry=0x7fff7fdff3a0, __in_chrg=<optimized out>) at io/qdebug.cpp:154
#8  0x00007ffff7e95ea1 in post_call_callback_gl (name=0xb071d2 "glTextureParameteri", funcptr=<optimized out>, len_args=<optimized out>) at /usr/include/qt5/QtCore/qdebug.h:129
#9  0x00000000009f30dd in glad_debug_impl_glTextureParameteri (arg0=6, arg1=32882, arg2=10497) at /home/dale/.conan2/p/b/glad382b84cb1af40/b/build/Debug/src/glad.c:5154
#10 0x00007ffff7e99669 in gpu::gl45::GL45Backend::GL45Texture::syncSampler (this=0x7ffeeb3b7f60) at /home/dale/git/overte/libraries/gpu-gl/src/gpu/gl45/GL45BackendTexture.cpp:315
#11 0x00007ffff7e9974c in gpu::gl45::GL45Backend::GL45FixedAllocationTexture::syncSampler (this=0x7ffeeb3b7f60) at /home/dale/git/overte/libraries/gpu-gl/src/gpu/gl45/GL45BackendTexture.cpp:364
#12 0x00007ffff7e99ee0 in gpu::gl45::GL45Backend::GL45FixedAllocationTexture::GL45FixedAllocationTexture (this=this@entry=0x7ffeeb3b7f60, backend=<optimized out>, texture=...) at /home/dale/git/overte/libraries/gpu-gl/src/gpu/gl45/GL45BackendTexture.cpp:330
#13 0x00007ffff7e99ef9 in gpu::gl45::GL45Backend::GL45AttachmentTexture::GL45AttachmentTexture (this=0x7ffeeb3b7f60, backend=<optimized out>, texture=<optimized out>) at /home/dale/git/overte/libraries/gpu-gl/src/gpu/gl45/GL45BackendTexture.cpp:373
#14 0x00007ffff7e9a199 in gpu::gl45::GL45Backend::syncGPUObject (this=0x7fffabf450d0, texturePointer=<optimized out>) at /home/dale/git/overte/libraries/gpu-gl/src/gpu/gl45/GL45BackendTexture.cpp:78
#15 0x00007ffff7e9854c in gpu::gl45::GL45Framebuffer::update (this=0x7fff318c5750) at /home/dale/git/overte/libraries/gpu-gl/src/gpu/gl45/GL45BackendOutput.cpp:57
#16 0x00007ffff7e976ce in gpu::gl::GLFramebuffer::sync<gpu::gl45::GL45Framebuffer> (backend=<optimized out>, framebuffer=...) at /home/dale/git/overte/libraries/gpu-gl-common/src/gpu/gl/GLFramebuffer.h:45
#17 gpu::gl::GLFramebuffer::getId<gpu::gl45::GL45Framebuffer> (backend=<optimized out>, framebuffer=...) at /home/dale/git/overte/libraries/gpu-gl-common/src/gpu/gl/GLFramebuffer.h:51
#18 gpu::gl45::GL45Backend::getFramebufferID (this=<optimized out>, framebuffer=<optimized out>) at /home/dale/git/overte/libraries/gpu-gl/src/gpu/gl45/GL45BackendOutput.cpp:136
#19 0x00007ffff53d0b4d in gpu::gl::GLBackend::setFramebuffer (this=0x7fffabf450d0, framebuffer=std::shared_ptr<gpu::Framebuffer> (use count 6, weak count 0) = {...}) at /home/dale/git/overte/libraries/gpu-gl-common/src/gpu/gl/GLBackendOutput.cpp:59
#20 gpu::gl::GLBackend::do_setFramebuffer (this=0x7fffabf450d0, batch=<optimized out>, paramOffset=<optimized out>) at /home/dale/git/overte/libraries/gpu-gl-common/src/gpu/gl/GLBackendOutput.cpp:45
#21 0x00007ffff53cc4ef in gpu::gl::GLBackend::renderPassTransfer (this=this@entry=0x7fffabf450d0, batch=...) at /home/dale/git/overte/libraries/gpu-gl-common/src/gpu/gl/GLBackend.cpp:351
#22 0x00007ffff53ccc86 in gpu::gl::GLBackend::render (this=0x7fffabf450d0, batch=...) at /home/dale/git/overte/libraries/gpu-gl-common/src/gpu/gl/GLBackend.cpp:559
#23 0x00007ffff4d7bd2c in gpu::Context::executeFrame (this=0x7fffabab1a90, frame=std::shared_ptr<gpu::Frame> (use count 1, weak count 0) = {...}) at /home/dale/git/overte/libraries/gpu/src/gpu/Context.cpp:146
#24 0x00007ffff7f000c9 in OpenGLDisplayPlugin::present (this=this@entry=0x7fffac018400, refreshRateController=std::shared_ptr<RefreshRateController> (use count 1, weak count 0) = {...}) at /home/dale/git/overte/libraries/display-plugins/src/display-plugins/OpenGLDisplayPlugin.cpp:716
#25 0x00007ffff7f05a74 in PresentThread::run (this=0x7fffabc49300) at /home/dale/git/overte/libraries/display-plugins/src/display-plugins/OpenGLDisplayPlugin.cpp:198
#26 0x00007ffff6af0906 in operator() (__closure=<optimized out>) at thread/qthread_unix.cpp:350
#27 (anonymous namespace)::terminate_on_exception<QThreadPrivate::start(void*)::<lambda()> > (t=<optimized out>) at thread/qthread_unix.cpp:287
#28 QThreadPrivate::start (arg=0x7fffabc49300) at thread/qthread_unix.cpp:310
#29 0x00007fffe32a91b7 in start_thread (arg=<optimized out>) at pthread_create.c:447
#30 0x00007fffe332b39c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
```
